parameters:
  reclass:
    storage:
      data_source:
        engine: local
      node:
        infra_kvm_node01:
          classes:
          - cluster.mcpdoc.infra.glusterfs
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          classes:
          - cluster.mcpdoc.infra.glusterfs
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          classes:
          - cluster.${_param:cluster_name}.infra.backup.server
          - cluster.mcpdoc.infra.glusterfs
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
        stacklight_log_node01:
          classes:
          - system.elasticsearch.client.single
          - system.kibana.client.single
        openstack_control_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_control_node02:
          params:
            linux_system_codename: xenial
        openstack_control_node03:
          params:
            linux_system_codename: xenial
        openstack_database_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.database.master
        openstack_database_node02:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.database.slave
        openstack_database_node03:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.database.slave
        openstack_message_queue_node01:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node02:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node03:
          params:
            linux_system_codename: xenial
        openstack_proxy_node01:
          params:
            linux_system_codename: xenial
        openstack_proxy_node02:
          params:
            linux_system_codename: xenial
        openstack_telemetry_node01:
          params:
            linux_system_codename: xenial
            ceilometer_create_gnocchi_resources: true
            redis_cluster_role: 'master'
        openstack_telemetry_node02:
          params:
            linux_system_codename: xenial
            redis_cluster_role: 'slave'
        openstack_telemetry_node03:
          params:
            linux_system_codename: xenial
            redis_cluster_role: 'slave'
        openstack_barbican_node01:
          classes:
            - service.dogtag.server.cluster.master
          params:
            mysql_cluster_role: master
            linux_system_codename: xenial
        openstack_barbican_node02:
          classes:
            - service.dogtag.server.cluster.slave
          params:
            mysql_cluster_role: slave
            linux_system_codename: xenial
        openstack_barbican_node03:
          classes:
            - service.dogtag.server.cluster.slave
          params:
            mysql_cluster_role: slave
            linux_system_codename: xenial
        openstack_dns_node01:
          params:
            linux_system_codename: xenial
        openstack_dns_node02:
          params:
            linux_system_codename: xenial
        ceph_mon_node01:
          params:
            ceph_public_address: ${_param:ceph_mon_node01_ceph_public_address}
        ceph_mon_node02:
          params:
            ceph_public_address: ${_param:ceph_mon_node02_ceph_public_address}
        ceph_mon_node03:
          params:
            ceph_public_address: ${_param:ceph_mon_node03_ceph_public_address}
        ceph_rgw_node01:
          params:
            ceph_public_address: ${_param:ceph_rgw_node01_ceph_public_address}
        ceph_rgw_node02:
          params:
            ceph_public_address: ${_param:ceph_rgw_node02_ceph_public_address}
        ceph_rgw_node03:
          params:
            ceph_public_address: ${_param:ceph_rgw_node03_ceph_public_address}
        openstack_compute_rack01:
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          repeat:
            count: 3
            ip_ranges:
              single_address: 10.11.1.1-10.11.10.255
              tenant_address: 10.12.1.1-10.12.10.255
            start: 1
            digits: 0
            params:
              single_address:
                value: <<single_address>>
              tenant_address:
                value: <<tenant_address>>
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
        ceph_osd_rack01:
          name: ${_param:ceph_osd_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
            - cluster.${_param:cluster_name}.ceph.osd
          repeat:
            count: 5
            ip_ranges:
              single_address: 10.11.11.1-10.11.20.255
              backend_address: 10.12.11.1-10.12.20.255
              ceph_public_address: 10.13.11.1-10.13.20.255
            start: 1
            digits: 0
            params:
              single_address:
                value: <<single_address>>
              backend_address:
                value: <<backend_address>>
              ceph_public_address:
                value: <<ceph_public_address>>
          params:
            salt_master_host: ${_param:reclass_config_master}
            ceph_crush_parent: rack01
            linux_system_codename: xenial

