parameters:
  _param:
    
    salt_api_password: "hovno12345!"
    salt_api_password_hash: "$6$PSRWaIbj$4BFqUAjhm/qYVhGQ.f8BEL6e6mJaPlmpvTdUMoEiiSAStSPJT3HHwcTq8iBOGyT17WZSAL0QMEu/BSgg4yX/Z0"
    # General
    rabbitmq_guest_password: "D7z0ygB7e5G9zzymLdBvxZ0d2YRl199H"
    galera_clustercheck_password: "FTUkGnGKr38EZKusxlgUDyaLdz8yvcDZ"
    # MAAS
    infra_postgresql_admin_user_password: 4jXF2Ve5DzaHj3ymSN7zFIKpvbeYi3Ce
    # Do not change below values as needed for prebuilt day01 image
    maas_admin_username: mirantis
    maas_admin_password: beFBXaejLMRIzCuwBSViWRCwpCRBQQsa
    maas_db_password: Z5bkBY0ylXmpTZx90ANg7M7zg14NTStW
    # StackLight
    alerta_admin_password_generated: zprbzkS0WmTLht7VB7Tq0dF55qmaSL5A
    grafana_password_generated: qnKeKrk7nDYFgV2HPhPgX4SB2fSvgasU
    mysql_grafana_password_generated: HgB3aJ3Hzi9XpSK0cRt4JAR8yRyWjGsX
    influxdb_stacklight_password_generated: tajgeSktXGYeJQTFtWYn1jn5LezFGBFa
    influxdb_admin_password_generated: iDHAMdSqYhXGlUywIXUu2VfiblTiPtSn
    influxdb_password_generated: C4XugFb0dghBEykeAtdb1tT2eGmXrpvL
    stacklight_log_keepalived_password_generated: g65lEdEHTjAz1jxXZBHY8Eq6Nk2EPur6
    stacklight_telemetry_keepalived_password_generated: eyWK6sUdimhJ4klwDS92pWFLCZZTzYRR
    keepalived_stacklight_monitor_vip_password_generated: HGgycU01kMZwGgc2qKiFg9F6BWQPfR9B
    keepalived_prometheus_vip_password_generated: BVfX9UhBV9sRbbYM06SCYHaQzMzYkqPE
    stacklight_monitor_rabbitmq_password_generated: cqwhK9q5LA7LXVr8PajvsLRtgAkfe5Ba
    stacklight_monitor_uchiwa_password_generated: X6ddCl3MF5rWGRVWBArPaBcVrIQL8zpC
    stacklight_monitor_keepalived_password_generated: NpWPcvFgGWTCKm74Qx1caPfVE5NXR7R9
    # OpenStack
    keepalived_openstack_telemetry_vip_password: G0W4Rq361AV4F6C8HitjKuHW2DGKnH5M
    horizon_secret_key_generated: jEx2l58tf0im6uWNgGUgDMtci0vjffGjaCeRJMGERmN3pYUQNSPQAXHtRSULHmp5
    keystone_swift_password_generated: rgDBJKCWgLkSHl8vP3shnhEAgZnGc8nx
    rabbitmq_openstack_password_generated: dtAl1NQc0L4YdIk2efI1argzaGH3r1m1
    heat_domain_admin_password_generated: vDX6eyXB93FyDAEcmdAMQGHf68Pf0nzp
    ceilometer_influxdb_password_generated: zB1LZyBB16Hh7G69NtaTAxc2g5AVDtJC
    billometer_secret_key_generated: 49KyexfLx8Rg12ebjCxrcBYsRYDufdseY4QTMwuMktzv4c9KX6VpJIywPGhPAyHC
    mysql_aodh_password_generated: vSkXW6mrAQqN4NN80j0bA1HtmfezQBNp
    mysql_cinder_password_generated: jPXVdhjuiidGEIe5ag7zT4jbmGSCaNQC
    mysql_ceilometer_password_generated: G2Sale70DX84nTncShE0PXHIBtzFdY8C
    mysql_glance_password_generated: yDXs3wAhw3B7cTDuBDQGijn9QBbkYUSQ
    mysql_gnocchi_password_generated: 1zfH3Hu0qNsvb88VDK4U6rPqggaXV2mr
    mysql_heat_password_generated: BnlAdF4LHuZ3VIbLhm79avCxw2km2HdU
    mysql_keystone_password_generated: fH1MmB7EB8sZhVBvfbCC0uVBNkLbFfMF
    mysql_neutron_password_generated: eN4Z5RFJn8BSIJpKIiASzFWWG8x4xREP
    mysql_nova_password_generated: VBDU9FvFUtEstMBBtRSFlYLd1LYRc07h
    mysql_panko_password_generated: j0yVaVgkVY7gEby5sesX7A9KKB7a7IFV
    mysql_designate_password_generated: wXnDesxXZqfj1MubcaEzGPf3suCyH5Qj
    keystone_service_token_generated: VmcvhA9zkECcyTDQ
    keystone_admin_password_generated: 9nr2BxqFEZBdHiIZW1nfs5DPfWYSMVRE
    keystone_ceilometer_password_generated: bW90jZitybWhsCaMvW6T1k1fjT4vaDW3
    keystone_cinder_password_generated: pUwqZLaujbjKCXBQgbFM71MWZPBdTjxs
    keystone_glance_password_generated: nldHPkT3pjyCafU4SHdhkZVPhE3jC6FQ
    keystone_gnocchi_password_generated: IezikAreY6ADHKGBc3Ue1P2sZhp9k3W5
    keystone_heat_password_generated: jhz4u1ghlUw2g3sTyBFd36xGKkgv4iGl
    keystone_keystone_password_generated: ER3ssHUFpyCD5WwqbBugWacvlJBCaFIp
    keystone_neutron_password_generated: 9fw9HglmNjPVMUM6gs6wXRPta3r02mNY
    keystone_nova_password_generated: 4C9LM2Fady91La9xkHHJgrH6J5gfGbnK
    keystone_aodh_password_generated: cBc05HywbjhNehz9b1QDUXB0qMQbXMJM
    keystone_panko_password_generated: gfL2w9TaecCJ1Re6utR2WniIkWxjfsKF
    keystone_barbican_password_generated: Ln5SDxFnQpFkHAIhm6BY6GN8p7zA99wR
    barbican_keepalived_vip_password_generated: Lj3CKbrB9I8U2rGzPIfsrmn9egC3iFAu
    mysql_barbican_password_generated: BjXBGeD28izmHAzaF74xLrjj8F9779Z2
    dogtag_password_generated: X5DUiaN6zbUxQd1V2dBPESIHJSHs6YE3
    barbican_memcache_secret_key_generated: GFRpSa94jmytXg1B
    keystone_designate_password_generated: 9MHhYZ14IiEdizHrYbc8a6KVF7cdNdj0
    ceilometer_secret_key_generated: VFtdQBB6ix7Z1YYq
    mongodb_ceilometer_password_generated: ygy2tXCqEDK6BLvT9FBzEYCbX06BS1Sh
    mongodb_admin_password_generated: pHFXCXRB2Cykc5kaZl6lYEELQpG4C7mY
    mongodb_shared_key_generated: 2zsdZFKtdm1RqWRaLvt6udsHHPp9g65R1BuMLl68efDe8Mz6Ad5PVcwyjU7FecUe
    openstack_metadata_password_generated: vTsNnlFGdr4WFAVD0fissYTTUfiEAFhk
    keystone_billometer_password_generated: EGMh2ZmXuF5fFlbxyblZ1z0SP3ttxT8b
    cinder_storage_secret_uuid_generated: "be1c47b0-7a07-49c8-9b0b-b89b78c35cbc"
    nova_storage_secret_uuid_generated: "8cccf97d-e677-469b-8dc7-993777d95584"
    nova_memcache_secret_key_generated: z6xYk51IbGnT3YgB
    cinder_memcache_secret_key_generated: NI29hKrzCRVdgWWg
    glance_memcache_secret_key_generated: p9LHng1gPC3G4rUL
    neutron_memcache_secret_key_generated: MjeB4BR1zD2p0WsW
    heat_memcache_secret_key_generated: 8kFLUy4p4agnanTa
    aodh_memcache_secret_key_generated: BbICUdk1fN15qYHd
    ceilometer_memcache_secret_key_generated: ndYeBQEIrAVBsIQf
    panko_memcache_secret_key_generated: iZHq4YEQBEPxJCKM
    gnocchi_memcache_secret_key_generated: x8XvXnCKj5GJEc0b
    openstack_telemetry_redis_password_generated: fRYrjfTILDdJ9bkgdcz65GMd5DG7RRqe
    tenant_telemetry_keepalived_vip_password:  dhf99E2PBiREJaGZQrdcI7V4UE5MA6Qk
    designate_domain_uuid_generated: "57e7e3c4-84fe-45ac-8556-596d7a9d88af"
    designate_memcache_secret_key_generated: 2X0di1gZCs3I5gcJ
    designate_pdns_api_key_generated: S5C4JdxIcHfpEssK
    powerdns_webserver_password_generated: C95zSbYDS2kzDENDtNmjhPYIAbBwl3M8
    # DriveTrain / CICD
    openldap_admin_password: uhtjsFWK5ZI1qBabxUfpwKxYldrr6wPv
    # Gerrit
    gerrit_ldap_bind_password: "${_param:openldap_admin_password}"
    openldap_config_password_generated: JPIbammgbEquCdVavxCW0WR2nGdKmTBB
    openldap_readonly_password_generated: ZAaAKYL1wnbmd5VycCZ369qv7YGRDkka
    jenkins_admin_password_generated: YUsvDGl2qt72saq4swHa8V58FZL5a1tr
    gerrit_admin_password_generated: ET5mfSDSYQnyreNhc0f36GgWCXJ4sjCD
    cicd_keepalived_vip_password_generated: AfC53bCTSZ2u3rAdiUPMfms6JXbeLHaf
    cicd_mysql_admin_password_generated: PD4CLfKP73ZHiwhMyhx7ZnQ0xynBsuvm
    cicd_mysql_gerrit_password_generated: MDQH2QJSXX3L8YRL4ZlxJnKxg3Y7rAaS
    jenkins_admin_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCp0evjOaK8c8SKYK4r2+0BN7g+8YSvQ2n8nFgOURCyvkJqOHi1qPGZmuN0CclYVdVuZiXbWw3VxRbSW3EH736VzgY1U0JmoTiSamzLHaWsXvEIW8VCi7boli539QJP0ikJiBaNAgZILyCrVPN+A6mfqtacs1KXdZ0zlMq1BPtFciR1JTCRcVs5vP2Wwz5QtY2jMIh3aiwkePjMTQPcfmh1TkOlxYu5IbQyZ3G1ahA0mNKI9a0dtF282av/F6pwB/N1R1nEZ/9VtcN2I1mf1NW/tTHEEcTzXYo1R/8K9vlqAN8QvvGLZtZduGviNVNoNWvoxaXxDt8CPv2B2NCdQFZp
    jenkins_admin_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEAqdHr4zmivHPEimCuK9vtATe4PvGEr0Np/JxYDlEQsr5Cajh4
      tajxmZrjdAnJWFXVbmYl21sN1cUW0ltxB+9+lc4GNVNCZqE4kmpsyx2lrF7xCFvF
      Qou26JYud/UCT9IpCYgWjQIGSC8gq1TzfgOpn6rWnLNSl3WdM5TKtQT7RXIkdSUw
      kXFbObz9lsM+ULWNozCId2osJHj4zE0D3H5odU5DpcWLuSG0MmdxtWoQNJjSiPWt
      HbRdvNmr/xeqcAfzdUdZxGf/VbXDdiNZn9TVv7UxxBHE812KNUf/Cvb5agDfEL7x
      i2bWXbhr4jVTaDVr6MWl8Q7fAj79gdjQnUBWaQIDAQABAoIBAFU3kU6yIna9BViH
      UX+S2ijtRBjZ68JjavEnp4xvo5h+nydcdT57q9lv/0nAi3g3gmXm/oJH+/ZU87HV
      zy+zP+t+umDSChUkPBZFL5jxpKyN7BhMrP1KzRuEGYd6vJE/nfY5g095P5vDgnpX
      o+SNg/YqrY1u8zgr/hnfRaV2/XyIDEEcQXTHseWTnnMQnULFU88xL8yq8ACT5GhK
      7A9m5ukfcU6d/fs/psz5Yqw5IQsWbv1yJ3/FKufPHlo2Nzh3/3eDAZUXvaBgf1so
      FWFpHtkry3OXOGaZ98HgF9hL0twS0pzMvuypdGUQAt6nyB1N5re4LK/MAOddqwEc
      1+NQzfECgYEA2ryEf0GLJdtiYs3F4HbwTwJVIXdyWv7kjYGeMkutzzAjXl6wx8aq
      kfqLJ7x7UkR5unZ1ajEbKBciAlSuFA+Gikn6a4Lv8h87aSnHpPd/2VSitRlI/gW7
      w4U4CL3Br1JyonU5WA7VYfTow7KnHBhdwm27RMA9uosyIpveQRpqSG0CgYEAxsAS
      wCQKrhuPq2YtGtFR7K4BL+N+0E1Vq6h49u1ukcgUe0GHVD3VzBypNCv7rWEVHzAg
      biCVi7PCjzZYW4fYZmzVD4JbFLVGOUu7aJwLaE4wDe72DNr6YZhcS+Ta98BP+x0q
      Wt34JNPDabRPfhXfhiCqnWjjod+4Zqx4VJVNgG0CgYB5EXL8xJhyAbW5Hk/x56Mm
      +BGKjoR7HS3/rMiU6hJv5SMObrbGPI3YcqZm/gn8BO6jaEGg30E6tWMbiyc270j2
      be/vZe/NQcAuevOHuX3IGvJb7nzaLO46UBgtrmnv0mCkzuFIfh1ZNKdI+i9Ie6wZ
      m4bVjNod0EGVqlQgELDXGQKBgB+NNmzSS++/6FrpaZesSzkrlnynvOYMoOETacCp
      iLgT70xx5q308w/oLORfZyDrHJNK7JsPCS6YZvadRgGh2zTHajuAEj2DWZaW8zV0
      MEtqvi44FU+NI9qCeYSC3FAgc5IF20d5nX8bLxaEzWnSxx1f6jX7BMgZ4AhMsP2c
      hiUxAoGAFaxn+t9blIjqUiuh0smSYFhLBVPZveYHQDmQYERjktptBd3X95fGnSKh
      iDe2iPGyud2+Yu4X/VjHLh/MRru+ZXvPXw1XwEqX93q8a1n283ul0Rl9+KKKOVHR
      eecTjI/BfXBf33mPRKny3xuHw6uwta2T3OXky9IhqYS1kkHiZWA=
      -----END RSA PRIVATE KEY-----
    # Ceph
    rgw_keepalived_vip_password_generated: py5tZYrGVHF
    ceph_cluster_fsid_generated: "2f14575b-9232-41e4-8312-7b021b8763e6"
    rabbitmq_admin_password_generated: ZahJ4i40shebSef6Nf7t2SaeSpKDPghd
    rabbitmq_secret_key_generated: SkQs8SbczJ1SF4zA
    galera_server_maintenance_password_generated: Z717GvDT9ZiSI6Q1ndhfGj1k4NPUjF2Y
    galera_server_admin_password_generated: ANy0XQTCfmYCcV08fN19xHXjexsfJGit
    galera_server_sst_password_generated: GkI26rfBuGGt67vaTcvFZdh4ahNh3Sim
    docker_registry_http_secret_generated: KtYF3DK5MpkCEpKd
    mysql_octavia_password_generated: wrfIHBFHWZF5SZit6vRIiDzNIHbEGNE3
    keystone_octavia_password_generated: 3dnH5ksiEuFpgdc17jGaBcxSEwd4S8N9
    amp_flavor_id_generated: BSNiAyn6fAkvEKY1
    octavia_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAtjnPDJsQToHBtoqIo15mdSYpfi8z6DFMi8Gbo0KCN33OUn5u
      OctbdtjUfeuhvI6px1SCnvyWi09Ft8eWwq+KwLCGKbUxLvqKltuJ7K3LIrGXkt+m
      qZN4O9XKeVKfZH+mQWkkxRWgX2r8RKNV3GkdNtd74VjhP+R6XSKJQ1Z8b7eHM10v
      6IjTY/jPczjK+eyCeEj4qbSnV8eKlqLhhquuSQRmUO2DRSjLVdpdf2BB4/BdWFsD
      YOmX7mb8kpEr9vQ+c1JKMXDwD6ehzyU8kE+1kVm5zOeEy4HdYIMpvUfN49P1anRV
      2ISQ1ZE+r22IAMKl0tekrGH0e/1NP1DF5rINMwIDAQABAoIBAQCkP/cgpaRNHyg8
      ISKIHs67SWqdEm73G3ijgB+JSKmW2w7dzJgN//6xYUAnP/zIuM7PnJ0gMQyBBTMS
      NBTv5spqZLKJZYivj6Tb1Ya8jupKm0jEWlMfBo2ZYVrfgFmrfGOfEebSvmuPlh9M
      vuzlftmWVSSUOkjODmM9D6QpzgrbpktBuA/WpX+6esMTwJpOcQ5xZWEnHXnVzuTc
      SncodVweE4gz6F1qorbqIJz8UAUQ5T0OZTdHzIS1IbamACHWaxQfixAO2s4+BoUK
      ANGGZWkfneCxx7lthvY8DiKn7M5cSRnqFyDToGqaLezdkMNlGC7v3U11FF5blSEW
      fL1o/HwBAoGBAOavhTr8eqezTchqZvarorFIq7HFWk/l0vguIotu6/wlh1V/KdF+
      aLLHgPgJ5j+RrCMvTBoKqMeeHfVGrS2udEy8L1mK6b3meG+tMxU05OA55abmhYn7
      7vF0q8XJmYIHIXmuCgF90R8Piscb0eaMlmHW9unKTKo8EOs5j+D8+AMJAoGBAMo4
      8WW+D3XiD7fsymsfXalf7VpAt/H834QTbNZJweUWhg11eLutyahyyfjjHV200nNZ
      cnU09DWKpBbLg7d1pyT69CNLXpNnxuWCt8oiUjhWCUpNqVm2nDJbUdlRFTzYb2fS
      ZC4r0oQaPD5kMLSipjcwzMWe0PniySxNvKXKInFbAoGBAKxW2qD7uKKKuQSOQUft
      aAksMmEIAHWKTDdvOA2VG6XvX5DHBLXmy08s7rPfqW06ZjCPCDq4Velzvgvc9koX
      d/lP6cvqlL9za+x6p5wjPQ4rEt/CfmdcmOE4eY+1EgLrUt314LHGjjG3ScWAiirE
      QyDrGOIGaYoQf89L3KqIMr0JAoGARYAklw8nSSCUvmXHe+Gf0yKA9M/haG28dCwo
      780RsqZ3FBEXmYk1EYvCFqQX56jJ25MWX2n/tJcdpifz8Q2ikHcfiTHSI187YI34
      lKQPFgWb08m1NnwoWrY//yx63BqWz1vjymqNQ5GwutC8XJi5/6Xp+tGGiRuEgJGH
      EIPUKpkCgYAjBIVMkpNiLCREZ6b+qjrPV96ed3iTUt7TqP7yGlFI/OkORFS38xqC
      hBP6Fk8iNWuOWQD+ohM/vMMnvIhk5jwlcwn+kF0ra04gi5KBFWSh/ddWMJxUtPC1
      2htvlEc6zQAR6QfqXHmwhg1hP81JcpqpicQzCMhkzLoR1DC6stXdLg==
      -----END RSA PRIVATE KEY-----
    octavia_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2Oc8MmxBOgcG2ioijXmZ1Jil+LzPoMUyLwZujQoI3fc5Sfm45y1t22NR966G8jqnHVIKe/JaLT0W3x5bCr4rAsIYptTEu+oqW24nsrcsisZeS36apk3g71cp5Up9kf6ZBaSTFFaBfavxEo1XcaR0213vhWOE/5HpdIolDVnxvt4czXS/oiNNj+M9zOMr57IJ4SPiptKdXx4qWouGGq65JBGZQ7YNFKMtV2l1/YEHj8F1YWwNg6ZfuZvySkSv29D5zUkoxcPAPp6HPJTyQT7WRWbnM54TLgd1ggym9R83j0/VqdFXYhJDVkT6vbYgAwqXS16SsYfR7/U0/UMXmsg0z
